public: true
type: "docs"
tags:
  - "processing"
  - "planning"
  - "project vitals"
slug: "processing_manual"
title: "Guide to Processing Collections at the RAC"
description: "A manual for arranging and describing archival collections."
