public: true
type: "docs"
tags:
  - "processing"
  - "planning"
  - "project vitals"
title: "Guide to Processing Collections"
description: "A manual for arranging and describing archival collections."
pages:
  - ["Rockefeller Archive Center Guide to Processing Collections", "index"]
  - ["Planning", "planning"]
  - ["Processing", "processing"]
