public: true
type: "docs"
title: "Processing Manual"
description: "A manual for arranging and describing archival collections."
pages:
  - ["Processing Manual", "index"]
  - ["Planning", "planning"]
  - ["Processing", "processing"]
